# .github/workflows/backend.yml
name: Backend CI

on:
  push:
    paths:
      - 'community-chatbot/scripts/**'
      - 'community-chatbot/requirements.txt'
  pull_request:
    paths:
      - 'community-chatbot/scripts/**'
      - 'community-chatbot/requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd community-chatbot
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend script
        run: |
          cd community-chatbot/scripts
          bash run_backend.sh || echo "No backend service started"
